ignorePatterns:
  - 'provision/**'
ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - husky
  - "@src/*"
  - "@src/.*"
  - rhachet
  - rhachet-roles-bhrain
  - rhachet-roles-bhuild
  - rhachet-roles-ehmpathy
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - tsx
  - tsc-alias
  - yalc
  - "@tsconfig/node-lts-strictest"
  - core-js
  - test-fns
  - ts-jest
  - ts-node
  - declastruct
  - declastruct-github
